import Link from 'next/link'
import { notFound } from 'next/navigation'
import { buildMetadata } from '@/lib/seo'
import { ArrowRightIcon } from '@/components/icons'
import { SiteFooter } from '@/components/site-footer'

const insights = {
  'software-starts-with-workflow': { category: 'Product thinking', title: 'Software starts with the workflow, not the screen', paragraphs: ['The fastest way to make software confusing is to design pages before understanding the work. Screens become containers for assumptions: which user is acting, what state the record is in, which exception is allowed and what happens next.', 'A workflow-first approach begins with the job. Map the actor, the input, the decision and the outcome. Then identify where the process branches. Only after that should the interface decide what belongs on a dashboard, a form, a modal or a separate view.', 'This approach is especially useful for business software because operational complexity compounds. A retail system may involve stock, serial numbers, payments, warranties and staff permissions at the same time. The UI becomes clearer when those relationships are modeled instead of hidden behind a collection of screens.'] },
  'from-app-to-business-system': { category: 'Architecture', title: 'The move from app to business system', paragraphs: ['A mobile app can be feature-complete while a business system can still be operationally immature. The difference is the need to preserve state, history and accountability over time.', 'As systems grow, architecture has to make ownership visible: which layer validates a rule, which component owns a transaction, where permissions are checked, and how a change is recorded. These are not glamorous problems, but they are what make software trustworthy in daily operations.', 'A mature business system also needs an information hierarchy that mirrors the work. Overview surfaces are for context; detail views are for decisions; action surfaces are for committed changes. Once that hierarchy is explicit, complexity becomes easier to navigate.'] },
  'design-for-maintenance': { category: 'Engineering', title: 'Designing for the next developer', paragraphs: ['Maintainability is a user-experience problem for the people who will change the software later. A component that is technically reusable but difficult to understand is not truly reusable.', 'Good maintenance begins with small signals: names that explain intent, predictable folder boundaries, consistent states, typed interfaces and visual tokens that make variations deliberate instead of accidental.', 'Production readiness is the same idea at a larger scale. The site, application, database and deployment pipeline should all expose enough structure that another engineer can understand the system without reverse-engineering every decision.'] },
} as const

export function generateStaticParams() { return Object.keys(insights).map((slug) => ({ slug })) }

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const item = insights[slug as keyof typeof insights]; return item ? buildMetadata({ title: item.title, description: item.paragraphs[0], path: `/insights/${slug}` }) : buildMetadata({ title: 'Insight not found', description: 'The requested insight could not be found.', path: `/insights/${slug}` }) }

export default async function InsightPage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const item = insights[slug as keyof typeof insights]; if (!item) notFound(); return <><main><section className="page-hero"><div className="shell page-hero__content"><div className="eyebrow"><span className="eyebrow__line" /> {item.category}</div><h1>{item.title}</h1><p>{item.paragraphs[0]}</p></div></section><section className="content-section"><div className="shell content-grid"><article className="content-copy">{item.paragraphs.slice(1).map((paragraph) => <p key={paragraph}>{paragraph}</p>)}<h3>Continue exploring</h3><p>Read the product portfolio and project pages for concrete examples of how these ideas translate into software systems.</p><Link className="button button--primary" href="/products">Explore products <ArrowRightIcon /></Link></article><aside className="content-aside"><span className="content-aside__label">Insights</span><h3>{item.category}</h3><p>Editorial content is intentionally separated from product facts so visitors and crawlers can distinguish viewpoint from portfolio evidence.</p></aside></div></section></main><SiteFooter /></> }
